### ISSUE TITLE
Error in "code-block" directive: Number of arguments supplied

### ISSUE THREAD

**Issue by ntolia** [adamtheturtle/sphinx-substitution-extensions#106]
I am using Sphinx 3.0.4 and Sphinx-Substitution-Extensions-2020.5.27.0. However, I am getting this error:

```
:Error in "code-block" directive:
maximum 1 argument(s) allowed, 2 supplied.

.. code-block:: console
    :substitutions:

...
```

What might I be doing wrong?

**Comment by ntolia** [comment]
A little bit more information and an easy repro. Seems like recent substitution changes introduce an incompatibility with https://github.com/djungelorm/sphinx-tabs. This used to work untill recently. Here is a diff against the sample code in this repo to easily reproduce the issue.

```
diff --git a/sample/source/conf.py b/sample/source/conf.py
index b513587..fc18c61 100644
--- a/sample/source/conf.py
+++ b/sample/source/conf.py
@@ -3,6 +3,7 @@ Sample ``conf.py``.
 """

 extensions = [
+    'sphinx_tabs.tabs',
     'sphinx-prompt',
     'sphinx_substitution_extensions',
 ]
diff --git a/sample/source/index.rst b/sample/source/index.rst
index 0c2f5a6..f2a9dad 100644
--- a/sample/source/index.rst
+++ b/sample/source/index.rst
@@ -7,6 +7,24 @@ Configuration
 .. literalinclude:: conf.py
    :language: python

+
+.. tabs::
+
+  .. group-tab:: Tab 1
+
+    .. code-block:: console
+        :substitutions:
+
+       echo "The author is |author|"
+
+  .. group-tab:: Tab 2
+
+    .. code-block:: console
+       :substitutions:
+
+       echo "The author is |author|"
+
+
 ``prompt``
 ----------
```

**Comment by adamtheturtle** [comment]
@ntolia This is a confusing error from Sphinx itself, but the issue is an easy fix:

```rst
.. code-block:: console
    :substitutions:
```

The indentation on this line is not correct.
Instead, it should be:

```rst
.. code-block:: console
   :substitutions:
```

In my fixed version, the `:substitutions:` option is in line with the start of the word `code-block`.

**Comment by adamtheturtle** [comment]
Please feel free to re-open this issue or create a new one if you continue to have problems.

**Comment by ntolia** [comment]
Argh, apologies for not noticing the whitespace difference.

**Comment by adamtheturtle** [comment]
No worries!
