### ISSUE TITLE
Compatibility issues with doc8

### ISSUE THREAD

**Issue by ntolia** [adamtheturtle/sphinx-substitution-extensions#107]
With the recent changes for how substitution in code-blocks works, this causes issues with the [doc8](https://github.com/PyCQA/doc8) project as `substitutions` shows up as invalid RST. Running in on the repository's sample code will show this error:

```
$ doc8 .
Scanning...
Validating...
./index.rst:55: D000 Error in "code-block" directive:
unknown option: "substitutions".
./_tmp/_sources/index.rst.txt:27: D002 Trailing whitespace
========
Total files scanned = 2
Total files ignored = 0
Total accumulated errors = 2
Detailed error counts:
    - CheckCarriageReturn = 0
    - CheckIndentationNoTab = 0
    - CheckMaxLineLength = 0
    - CheckNewlineEndOfFile = 0
    - CheckTrailingWhitespace = 1
    - CheckValidity = 1
```
Not sure if there are any options here apart from trying to patch doc8 with something similar to [this change](https://github.com/PyCQA/doc8/commit/e932606c5c9db4bc759833ed1fc76c5d0701b163) that ignores `caption` for code-block.

**Comment by ntolia** [comment]
I created a doc8 patch and opened a PR at https://github.com/PyCQA/doc8/pull/34.

**Comment by adamtheturtle** [comment]
Nice PR! It has been accepted into doc8. I will add doc8 linting to this repo once a doc8 release is done.

**Comment by ntolia** [comment]
Happy to help and thanks again for maintaining this extension. It is very helpful!

I am going to close this issue out given the upstream merge. Folks can always do a `pip install` from GitHub if they run into this.

**Comment by ntolia** [comment]
@adamtheturtle Just FYI, doc8 has a new release with my fix.

**Comment by adamtheturtle** [comment]
😄 thanks @ntolia !
