### ISSUE TITLE
sphinx warning about 'safe for parallel reading'

### ISSUE THREAD

**Issue by rscohn2** [adamtheturtle/sphinx-substitution-extensions#170]
When I process a big complicated document, I see this warning: 

```
  sphinx-build -M html ./source ./build -N -j auto -q
WARNING: the sphinx_substitution_extensions extension does not declare if it is safe for parallel reading, assuming it isn't - please \
ask the extension author to check and make it explicit
WARNING: doing serial read
```
I tried to make a simple doc to reproduce the problem, but I don't get the message. Has anyone seen this warning and knows what triggers it and how to resolve it? I am using:
Sphinx-Substitution-Extensions==2020.7.4.1

**Comment by adamtheturtle** [comment]
> Has anyone seen this warning and knows what triggers it

From reading the Sphinx source code I can see that this happens when the number of jobs is > 1 and when there are > 5 documents that Sphinx has to build.

https://github.com/sphinx-doc/sphinx/blob/4c1b8b8db6fa25afcab1a6a3634776009cfafddf/sphinx/builders/__init__.py#L410
