### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by winksaville** [adamtheturtle/sphinx-substitution-extensions#179]
I'd like to suggest changing to [semver](https://semver.org/) so that its sphinx-substitution-extensions is compatible with semver support in python as specified in [pep 440](https://www.python.org/dev/peps/pep-0440/#version-specifiers).

**Comment by adamtheturtle** [comment]
Hi @winksaville - thank you for the suggestion. What would the benefit of this to you as a user?

**Comment by adamtheturtle** [comment]
@winksaville I'm closing but please do reopen if you would like to describe the benefit to you.
