### ISSUE TITLE
:substitutions: option for Sphinx's code-block directive not working under sphinx-panel's tabbed directive

### ISSUE THREAD

**Issue by zainhaq-h2o** [adamtheturtle/sphinx-substitution-extensions#243]
`:substitutions:` option for Sphinx's `code-block` directive does not appear to be working under `sphinx-panel`'s `tabbed` directive. If the `substitutions` option is used, the code block does not appear at all underneath the tab. For more info on the `tabbed` directive, see https://sphinx-panels.readthedocs.io/en/latest/#tabbed-content.

**Comment by adamtheturtle** [comment]
Thank you for the report @zainhaq-h2o . `sphinx-panels` is now unmaintained, and the documentation points to [`sphinx-design`](https://github.com/executablebooks/sphinx-design).

I tested a substitution within a `sphinx-design` tab, and it works, so I am closing this issue.
