### ISSUE TITLE
Enabling This Incorrectly Applies a Substitution to All Types in API Docs

### ISSUE THREAD

**Issue by alexdlaird** [adamtheturtle/sphinx-substitution-extensions#719]
I enabled this extension for a single variable on my project, `pyngrok_version`. All I changed was adding the extension, adding this to `conf.py`:

```python
rst_prolog = """
.. |pyngrok_version| replace:: {pyngrok_version}
""".format(pyngrok_version=version)
```

And then in my `troubleshooting.rst` file, I have this line now where the substitution should occur:

```rst
.. code-block:: shell
    :substitutions:

    ...

    PYNGROK VERSION:
       |pyngrok_version|
```

And that works great, the version `7.1.5` now appears there and will auto-update! Unfortunately, with no other configuration change (here is [the commit](https://github.com/alexdlaird/pyngrok/commit/07da963ef88f81f0d959f72daae1d87e22e11456)), my API docs all look like this now:

<img width="400" alt="Screenshot 2024-03-10 at 7 53 33 AM" src="https://github.com/adamtheturtle/sphinx-substitution-extensions/assets/1660326/9030faf9-2f7d-44f4-903a-c16167378448">
<img width="400" alt="Screenshot 2024-03-10 at 7 53 44 AM" src="https://github.com/adamtheturtle/sphinx-substitution-extensions/assets/1660326/f018d23a-082e-4d75-9f1c-9534b284c318">

All types now appear to also have this substitution applied. They used to look like like:

<img width="200" alt="Screenshot 2024-03-10 at 7 53 55 AM" src="https://github.com/adamtheturtle/sphinx-substitution-extensions/assets/1660326/600cef89-53a6-4ed8-aece-6d304340c16a">

I disabled this on my `main` branch so `latest` would be stable again, so you can see how the API docs are supposed to look [here](https://pyngrok.readthedocs.io/en/latest/api.html). Then I enabled a hidden branch on ReadTheDocs so you can see them broken [here](https://pyngrok.readthedocs.io/en/sphinx-substitution-extensions/api.html).

**Comment by adamtheturtle** [comment]
Thank you @alexdlaird for the detailed report.

I don't think that this is a problem with `sphinx-substitution-extensions`, but instead I think that it is a problem with `sphinx_autodoc_typehints`.

If I take your project at `main`, and then add only:

```python
# end of conf.py
rst_prolog = """
.. |something| replace:: 7.1.5
"""
```

You will see that the error you posted occurs.

**Comment by alexdlaird** [comment]
Great find. I'll try some things out without your extension enabled and may open a bug for them over there as well, as it doesn't just seem like the extensions are incompatible with each other, it seems like their typedoc hints are causing an overly-greedy replacement.

**Comment by adamtheturtle** [comment]
I'll close this issue now then, and I'm open to more issues. Good luck!

**Comment by alexdlaird** [comment]
This issue over there references the same problem (manifest differently): https://github.com/tox-dev/sphinx-autodoc-typehints/issues/425

It appears this PR of theirs broke it: https://github.com/tox-dev/sphinx-autodoc-typehints/pull/422

Solution (until they fix it), pin the version back, where it works fine with or without your library:

```
sphinx_autodoc_typehints==1.25.2
```
