### ISSUE TITLE
Don't pin requirements

### ISSUE THREAD

**Issue by danwos** [adamtheturtle/sphinx-substitution-extensions#72]
Thanks for this helpful extension! :+1: 

I have a problem with your dependency setup, as it requires specific versions:
```
docutils==0.16
sphinx-prompt==1.1.0
sphinx==2.4.4
```
So when using sphinx 2.4.3, I can't install your plugin. Even if it would work.

Maybe you can set the version not so strict.
E.g. if you know your plugin does not work with Sphinx < 2, set it like 
```sphinx>=2```

Currently I can't install your plugin, because I'm using sphinx 2.4.4, but the released version on pypi is requesting 2.4.2

**Comment by adamtheturtle** [comment]
Thanks @danwos.
I'm always torn about this because I don't know for sure that this will work with all versions of `Sphinx` `>=` version 2.

That said:

1. I will do a release which supports the latest version
2. If you wish to submit a pull request, I will likely accept it

**Comment by danwos** [comment]
The problem with releases for latest version is, that the latest version of sphinx is a moving target and you need to release the same code ever and ever again, if sphinx creates a new version. Even if your code doesn't got any changes in the meantime.

Also why throwing the support out for a tested, but older version, if no changes were made?

I'm also maintainer of some sphinx extensions and I never had the problem that something was not working because of a supported, but not tested version.
Only sphinx version with api changes, e.g. 1.8., got thrown out by the time, as my extension started to use functions from 2.x only.
See https://github.com/useblocks/sphinxcontrib-needs for some ideas how version managing can be done.

And if you need to test for different versions of sphinx, tox is your awesome friend:
https://tox.readthedocs.io/en/latest/
Created a small PR to implement it and now tox tests for everything with the different sphinx versions between 2.x and <3. See #71 


Also the Sphinx API stays stable between major versions. So what worked for 2.1 should also work for 2.2, 2.3 and 2.4 (if not, you maybe use internal sphinx functions, which have changed.)

Also for a lib/extentsion your requested versions should be so unspecific as possible, so that in combination with other libs/extensions there are no unsolvable dependency chains created.
Just think about you need 5 sphinx-extensions and every extension would strongly pin the needed versions for sphinx and docutils. The chance that they are all pinning the same versions is nearly zero. Only for standalone applications this strong pinning would be fine :)

**Comment by adamtheturtle** [comment]
Thank you @danwos for the detailed and convincing explanation. I would rather avoid another intermediary layer (`tox`) and do this with the Github Actions workflow. However, I will fall back to `tox` if needed!

**Comment by adamtheturtle** [comment]
@danwos I have now made the pins much less specific. I still feel a little uncomfortable and do not want a huge CI matrix, but it is all good for now. Thanks for you help and work, and patience with the responses!
