### ISSUE TITLE
Perform a release for sphinx 8 compatibility

### ISSUE THREAD

**Issue by wouterdb** [adamtheturtle/sphinx-substitution-extensions#856]
Currently, `sphinx-substitution-extensions` is compatible with sphinx 8, but [sphinx-prompt](https://github.com/sbrunner/sphinx-prompt) is not. 

The dependency on sphinx prompt has been removed, but not released yet.

This is preventing us from updating to sphinx 8.

Thank you.

**Comment by adamtheturtle** [comment]
`2024.8.6` has just been released.
