### ISSUE TITLE
Support the {{ }} substitution syntax from MyST

### ISSUE THREAD

**Issue by neongreen-sc** [adamtheturtle/sphinx-substitution-extensions#977]
When using substitutions with MyST, `{{ }}` is used for substitutions in normal text -- but for code blocks I still have to use `| |`. Can this be made configurable?

**Comment by adamtheturtle** [comment]
Thank you for the issue. I've never used MyST outside of the testing for this project, so it is new to me. It seems I got it wrong by forcing `|`.

It looks like the important setting is not to use `{` but instead to use the value of the `myst_sub_delimiters` configuration variable which defaults to `{`, and is described at https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#substitutions-with-jinja2.

My thinking is to support the `myst_sub_delimiters` configuration variable (therefore enabling `{{ }}` substitutions), and to continue supporting `| |` substitutions as well, for backwards compatibility.

**Comment by adamtheturtle** [comment]
@neongreen-sc Please try `sphinx-substitution-extensions== 2024.10.17` and create a new issue if there are any problems.
